name: sakura_jisho
description: This is the culmination of everything i am

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Images
  assets:

    #Adverb background section image
    - images/fuji_img.jpg

    #Sustantives background section image
    - images/japanese_crowded_town_img.jpeg

    #Counters background section image
    - images/japanese_lamps_img.jpeg

    #Adjetives background section image
    - images/japanese_town_img.jpeg

    #Main Screen and general background image
    - images/sakura_welcome_bg.jpg

    #Dictionary background section image
    - images/sakura_temple_img.jpeg

    #Verbs background section image
    - images/shrimp_img.jpeg



  # Fonts:
  fonts:

    #Sakura logo font
    - family: Hayley
      fonts:
        - asset: fonts/HayleySignature.ttf

    #General font
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    #Japanese text font
    - family: Aozora
      fonts:
        - asset: fonts/AozoraMinchoMedium.ttf
        - asset: fonts/AozoraMincho-Bold.ttf
          weight: 700

